### ISSUE TITLE
USER STORY: Anonymous poll feedback

### ISSUE THREAD

**Issue by JackSummerfield1** [JackSummerfield1/My-First-Agile-Project#5]
As a **user** I can **choose to hide my identity in a poll** so that **I can provide anonymous feedback**

### Acceptance Criteria
- The option should be provided as a checkbox
- The option should be 'checked' by default
- The option should appear next to the submit button
- The user should receive a confirmation message after submission, including their user name

### Tasks
- [ ] Update the view; the poll design to show the name of the submitter and include the checkbox (HTML & CSS)
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update test scripts
- [ ] Test functionality
